// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5YolZRQnmSVWy6nvfdQSUzcF423nXSIU',
    appId: '1:82505710091:web:5be2be47fad300f07da50e',
    messagingSenderId: '82505710091',
    projectId: 'flutterauthen-ffa32',
    authDomain: 'flutterauthen-ffa32.firebaseapp.com',
    storageBucket: 'flutterauthen-ffa32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYzBEzkB-N29LD-By09Qf1b_-RrPNSgeg',
    appId: '1:82505710091:android:6476215af31e1e607da50e',
    messagingSenderId: '82505710091',
    projectId: 'flutterauthen-ffa32',
    storageBucket: 'flutterauthen-ffa32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqnr3snJd9RumPqG0ubv-W7tbPyXOY1U',
    appId: '1:82505710091:ios:65a7f54549d57f227da50e',
    messagingSenderId: '82505710091',
    projectId: 'flutterauthen-ffa32',
    storageBucket: 'flutterauthen-ffa32.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqqnr3snJd9RumPqG0ubv-W7tbPyXOY1U',
    appId: '1:82505710091:ios:cd2d621e25b2a0317da50e',
    messagingSenderId: '82505710091',
    projectId: 'flutterauthen-ffa32',
    storageBucket: 'flutterauthen-ffa32.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
